config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pages/index'

  resources :usuarios

  root 'usuarios#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base

  validates :nombre, presence: true
  validates :apellido, presence: true
  validates :numero_de_reparacion, presence: true, uniqueness: true, length: {maximum: 9,
                                                                                too_long: "%{count} caracteres es lo maximo permitido"}
  validates :estado, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :apellido, :numero_de_reparacion, :estado)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LaserApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="shortcut icon" href="/favicon.ico"/>


  <link rel="stylesheet" type="text/css" href="/assets/bootstrap.min.css"/>

  <link rel="stylesheet" type="text/css" href="/assets/global.css"/>

  <link rel="stylesheet" type="text/css" href="/assets/typo.css"/>

  <link rel="stylesheet" type="text/css" href="/assets/colorbox.css"/>

  <link rel="stylesheet" type="text/css" href="/assets/boxes.css"/>

  <link rel="stylesheet" type="text/css" href="/assets/social.css"/>


  <!--Fonts-->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&amp;subset=latin,cyrillic'
        rel='stylesheet' type='text/css'/>

  <!--Fonts with Icons-->
  <link rel="stylesheet" href="/assets/fontello.css"/>
</head>
<body>

<%= yield %>

</body>

<script src="/assets/jquery-1.11.0.min.js"></script>
<script src="/assets/bootstrap.min.js"></script>
<script src="/assets/requestAnimationFramePolyfill.min.js"></script>
<script src="/assets/jquery.easing.1.3.js"></script>
<script src="/assets/jquery.scrollTo.min.js"></script>
<script src="/assets/jquery.colorbox-min.js"></script>
<script src="/assets/pi.global.js"></script>

</html>

app/views/pages/index.html.erb
<body>

<div id="pi-all">


<div id="page"><!-- - - - - - - - - - SECTION - - - - - - - - - -->
  <div class="pi-section-w pi-section-white piICheck piStylishSelect" style="background: #f4f6f6;">
    <div class="pi-section pi-padding-bottom-60">

      <div class="pi-text-center pi-margin-bottom-50">
        <h1 class="pi-uppercase pi-weight-700 pi-has-border pi-has-tall-border pi-has-short-border">
          AREA CLIENTES
        </h1>
        <p>Por favor ingrese en número de reparación proporcionado:</p>
      </div>

      <!-- Row -->
      <div class="pi-row">

        <!-- Col 4 -->
        <div class="pi-col-md-4 pi-col-md-offset-4 pi-col-sm-6 pi-col-sm-offset-3 pi-col-xs-8 pi-col-xs-offset-2">

          <!-- Box -->
          <div class="pi-box pi-round pi-shadow-15">

            <!-- Email form -->
            <div class="form-group">
              <div class="pi-input-with-icon">
                <div class="pi-input-icon"><i class="icon-mail"></i></div>
                <input type="email" class="form-control" id="exampleInputEmail" placeholder="E-mail">
              </div>
            </div>
            <!-- End email form -->

            <!-- Password form -->
            <div class="form-group">
              <div class="pi-input-with-icon">
                <div class="pi-input-icon"><i class="icon-lock"></i></div>
                <input type="password" class="form-control" id="exampleInputPassword" placeholder="Password">
              </div>
            </div>
            <!-- End password form -->

            <p class="pi-pull-right pi-small-text">
              <a href="#">
                Forgot password?
              </a>
            </p>

            <!-- Checkbox -->
            <div class="checkbox">
              <label class="pi-small-text">
                <input type="checkbox">Remember me
              </label>
            </div>
            <!-- End checkbox -->

            <!-- Submit button -->
            <p>
              <button type="submit" class="btn pi-btn-base pi-btn-wide pi-weight-600">
                Sign In
              </button>
            </p>
            <!-- End submit button -->

          </div>
          <!-- End box -->

          <p class="pi-text-center">
            Don't have Account? <a href="#" class="pi-weight-600">Sign Up</a>
          </p>

        </div>
        <!-- End col 4 -->

      </div>
      <!-- End row -->

    </div>
  </div>
  <!-- - - - - - - - - - END SECTION - - - - - - - - - --></div>



</body>

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :numero_de_reparacion %><br>
    <%= f.number_field :numero_de_reparacion %>
  </div>
  <div class="field">
    <%= f.label :estado %><br>
    <%= f.text_area :estado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<div id="pi-all">


  <div id="page"><!-- - - - - - - - - - SECTION - - - - - - - - - -->
    <div class="pi-section-w pi-section-white piICheck piStylishSelect">
      <div class="pi-section pi-padding-bottom-60">

        <!-- Row -->
        <div class="pi-row">

          <!-- Col 4 -->
          <div class="pi-col-md-4 pi-col-md-offset-4 pi-col-sm-6 pi-col-sm-offset-3 pi-col-xs-8 pi-col-xs-offset-2">

            <!-- Box -->
            <div class="pi-box pi-round pi-shadow-15" style="background-color: rgb(29, 29, 29); margin-top: -60px;">

              <!-- Email form -->
              <div class="form-group">
                <div class="pi-input-with-icon">
                  <div class="pi-input-icon"></div>


                  <%= form_tag usuarios_path, :method => 'get' do %>

                      </div>
                      </div>

                      <p>
                        <%= text_field_tag :search, params[:search], :class => 'form-control input', :placeholder=>'Ingrese nro....' %><br/><br/>
                        <%= submit_tag "Ver estado", :class => 'btn pi-btn-base pi-btn-wide pi-weight-600' %>
                      </p>
                  <% end %>


                  </div>

          </div>
          <!-- End col 4 -->

        </div>


        <div class="pi-text-center" style="margin-top: -44px;">
          <% nro=params[:search] %>

          <% @usuarios.each do |usuario| %>

              <% if usuario.numero_de_reparacion.to_s == nro.to_s %>
                  <br/><br/>

                  <h3 style="color: blue"> <%= 'Hola '+ usuario.nombre.capitalize + ' ' + usuario.apellido.capitalize+'!' %></h3>

                  <h3>Estado de la reparación</h3>

                  <p><%= usuario.estado %></p>

              <% else %>


              <% end %>

          <% end %>
        </div>
      </div>
      <!-- End row -->

    </div>
  </div>
  <!-- - - - - - - - - - END SECTION - - - - - - - - - --></div>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @usuario.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @usuario.apellido %>
</p>

<p>
  <strong>Numero de reparacion:</strong>
  <%= @usuario.numero_de_reparacion %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @usuario.estado %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>